### ISSUE TITLE
Randomly failing test detected

### ISSUE THREAD

**Issue by huiwang** [Manwe56/competitive-programming#1]
Failed tests:   doesNotTimeOutBeforeTimeoutReached(competitive.programming.timemanagement.TimerTest)

Tests run: 17, Failures: 1, Errors: 0, Skipped: 0

In the first build, I got this error and second build passes.

**Comment by Manwe56** [comment]
Should be OK now. It's not easy to deal with timing tests...If you have suggestions to enhance, don't hesitate!

**Comment by huiwang** [comment]
No solutions but get some ideas. In short, with a 1000$ server, it still takes 30 nanos to call System.nanoTime(), so don't try to measure anything which could last less than 30 nanos. 

http://shipilev.net/blog/2014/nanotrusting-nanotime/
https://blogs.oracle.com/dholmes/entry/inside_the_hotspot_vm_clocks
