### ISSUE TITLE
Etat incohérent à cause du timeout

### ISSUE THREAD

**Issue by racam** [Manwe56/competitive-programming#10]
Salut :)

J'ai découvert ton repo après avoir visionné ta video de devoxx sur le sujet. Je participe aussi aux contests de codingame et je suis imprésionner par ton repo ! sacré boulot !

Je fais actuellement le challenge "Tron". Dedans, à chaque "turn" tu n'as pas l'état du jeu, mais juste une mise à jour de la position courrante des joueurs. 
Ainsi il est lourd de recréer une instance de IGame à chaque turn. Il préférable d'utiliser le même objet IGame tout du long de la partie et à chaque turn et de le mettre à jour avec les nouvelles positions des joueurs.

Cependant, avec ton implémentation de Min(i)Max/MaxNTree (j'ai pas regardé TreeSearch) en Java, tu ne procédes pas à un `move.cancel(game);`  en cas de `TimeoutException` sur ta cascade d'appels récursifs effectués. Ainsi quand tu sors de ton turn, l'objet IGame n'est pas dans un état cohérent et ne peux pas être réutiliser pour les prochains tours.

Une solution simple pour l'implémentation Min(i)Max Java :
dans la fonction `evaluateSubPossibilities`

```Java
try {
    final MinMaxEvaluatedMove bestSubChild = minimax();
    child = new MinMaxEvaluatedMove();
} 
catch (final AlphaBetaPrunningException e) {} 
catch (final TimeOutException e) { throw new e;}
finally { move.cancel(game);}

if (child != null) {
    // Alpha beta prunning
    if (alphaBetaAtThisLevel) {
        if (player) { alpha = Math.max(alpha, child.getValue());}
        else { beta = Math.min(beta, child.getValue());}
        if (beta <= alpha) {
            //move.cancel(game);
            throw new AlphaBetaPrunningException();
        }
    }
    moves.add(child);
    //move.cancel(game);
}
} // boucle for
return moves;
```

Si on catch ou pas une exception dans tous les cas (finally) on effectue `move.cancel(game)`. Si c'est une `TimeoutException` on continue de la remonter. J'ai un refactoriser ton algo au passage :)

Je me permet de parler en Français car je sais que tu l'es. S'il faut continuer en anglais no problem. 
J'ai pas fait de PR car si ce "bug" est en faite une feature, je serai un peu frustré d'avoir sortie l'artillerie lourde ^^.

En tout cas ton repo m'inspire pas mal :) j'ai pas mal d'idées de refactorisation pour gagner un peu en perf. Et puis ajouter deux implémentations pour tes algos multijoueurs ( nbJoueurs > 2 comme maxn) : Paranoid et BRF (Best-Reply First). Mais bon comment peut-on faire ? Une issue par idée qui se transforme en PR si validée ?

**Comment by Manwe56** [comment]
Salut!

Merci pour tout les détails :). Habituellement je vais au plus vite lorsque je rentre dans la zone de timeout, et je ne rencontre pas de problèmes car je repart d'un nouvel IGame a chaque début du jeu.

Mais je comprends tout a fait ton point de vue, et je pense que tu peux simplement faire une PR pour l'intégrer dans le repo. Ajoute un test unitaire au passage pour couvrir les cas. Attention il ne faut en particulier pas utiliser le résultat de la dernière profondeur lorsqu'on détecte un timeout (on a pas parcouru tout l'arbre).

Si t'as d'autres idées n'hésite pas à les passer en PR! Je me trompe peut être, mais il me semble que Paranoid et BRF seraient des implémentations du IScoreConverter qu'on donnerais non? Ce serais en effet assez pratique :)
