### ISSUE TITLE
add a multi-disk collision simulation module

### ISSUE THREAD

**Issue by huiwang** [Manwe56/competitive-programming#5]
This simulation module should be useful for contests such as pockerchip and strikeback where we can simulate collisions among multiple disks.

@Manwe56 do you find it useful ?

**Comment by Manwe56** [comment]
Hi Hui,

Yes that would be certainly great. I'm not finding the pull request, can you create one?

Manwe

**Comment by huiwang** [comment]
@Manwe56 the pull request is ongoing. I'm testing the simulation system with the strikeback contest. Once finished, I'll create a PR :)

**Comment by Manwe56** [comment]
Hi Hui,

Tell me when the PR is ready. In the meantime I close the issue :)
